---
abstract: 'load archived messages from lingr.com'
author:
  - 'Toshio Ito <toshioito@cpan.org>'
build_requires:
  Exporter: 0
  List::Util: 0
  Module::Build::Pluggable::CPANfile: 0.02
  Test::Exception: 0.31
  Test::MockObject: 1.20120301
  Test::More: 0.98
  Try::Tiny: 0.16
  lib: 0
configure_requires:
  Module::Build: 0.40
  Module::Build::Pluggable: 0.09
  Module::Build::Pluggable::CPANfile: 0.02
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Lingr-Archives
no_index:
  directory:
    - t
    - xt
    - eg
    - inc
provides:
  WebService::Lingr::Archives:
    file: lib/WebService/Lingr/Archives.pm
    version: 0.01
requires:
  Carp: 0
  Furl: 2.18
  JSON: 2.53
  URI: 1.59
  perl: 5.010
resources:
  repository: git://github.com/debug-ito/WebService-Lingr-Archives.git
version: 0.01
